import Head from "next/head";
import { useRouter } from "next/router";
import Chat from "../chat";
import useProtectedChat from "../../hooks/useProtectedChat";

export default function ChatPage() {
  const router = useRouter();
  const { chat_id } = router.query;

  ////// temporary hack to see how it looks with data
  //   const { isLoading, chat } = useProtectedChat(chat_id as string);
  //////

  return (
    <div className="h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col justify-between h-full">
        {/* {chat ? (
          <Chat type={TaskCardTypes.extended} task={task} />
        ) : (
          <p>no data</p>
        )} */}
      </div>
    </div>
  );
}
