POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name": "Franz",
    "email": "test@test.com",
    "password": "password"
}

###

POST http://localhost:3000/api/auth/login

{
    "email": "test@test.com",
    "password": "password"
}

###

GET http://localhost:3000/api/user/
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNzg2NmU0OWUtZWY3Zi00ZDJlLThmYmItMjNhMWRmNGQ4NTZjIiwiZW1haWwiOiJ0ZXN0QHRlc3QuY29tIiwiaWF0IjoxNjY4NzY4NDMzLCJleHAiOjE2Njg4NTQ4MzN9.P4bGOsTAQPJVzdkGJzUQWegSVl0bWrrypBMsrpee7ak