# @name login
POST http://localhost:3000/api/auth/login
content-type: application/json

{
    "email": "mustafa@mustafa.com",
    "password": "test123"
}

###

@authToken = {{login.response.body.token}}
@userId = {{login.response.body.userId}}

# @name conversations
GET http://localhost:3000/api/chat
Authorization: {{authToken}}

###

@conversationId = {{conversations.response.body.$[0].id}}


POST http://localhost:3000/api/chat/{{conversationId}}/createMessage
Content-Type: application/json

{
    "content": "Hello",
    "authorId": "{{userId}}"
}

###

GET http://localhost:3000/api/chat/{{conversationId}}/getMessages

